model:
  name_or_path: Qwen/Qwen2.5-3B-Instruct
  revision: aa8e72537993ba99e69dfaafa59ed015b17504d1
fold: 1
num_train_epochs: 2
learning_rate: 0.00005
gradient_accumulation_steps: 8
max_sequence_length: 4096
save_steps: 10
seed: 42
